### ISSUE TITLE
关于len_dataloader的问题

### ISSUE THREAD

**Issue by kikiYa99** [fungtion/DANN_py3#10]
您好，我想请问一下，在main中len_dataloader取得是min（len(dataloader_souce),len(dataloader_target)）,一般来说目标域的数据要少于源域，那这样取循环的话，每次epoch源域不是都没有输入所有的样本嘛。那这样训练的话不就只使用了源域样本的一部分嘛？

**Comment by fungtion** [comment]
`shuffle` operation [here](https://github.com/fungtion/DANN_py3/blob/master/main.py#L54)

**Comment by kikiYa99** [comment]
所以这样的意思是，虽然每次的epoch没有取完所有的源域样本，但是因为样本随机，所以在多个epoch之后仍然被全部都训练了是嘛？

**Comment by fungtion** [comment]
Yes, you can customize a sampler to make all the data get trained.

**Comment by kikiYa99** [comment]
好的明白了，谢谢！
