### ISSUE TITLE
what's the difference between x.view_as(x) and x?

### ISSUE THREAD

**Issue by NotF404** [fungtion/DANN_py3#2]
hi fungtion!

`class ReverseLayerF(F):

    @staticmethod
    def forward(ctx, x, alpha):
        ctx.alpha = alpha
        return x.view_as(x)`

As the title says, why just return x, thanks for your concern

**Comment by fungtion** [comment]
If input and output is the same, the backward function cannot be recalled. In this case, we don't want to change the value of x in the forward, so we have to pass its value in another variable x.view_as(x).

**Comment by NotF404** [comment]
i gotit, thanks
