### ISSUE TITLE
关于模型classifier中dropout的问题

### ISSUE THREAD

**Issue by SupeRuier** [fungtion/DANN_py3#3]
model.py中第23行使用了dropout2d，但是在全连接层情况下不是应该使用dropout吗？这个时候应该也没有channel来dropout了吧？望解答。

**Comment by fungtion** [comment]
You are right, it has been fixed in https://github.com/fungtion/DANN_py3/commit/5066239fe26c2a2c5c56eb3d6c1c5e3a138d468d.
