### ISSUE TITLE
Pytorch version is not consistent in README and Dockfile

### ISSUE THREAD

**Issue by HuGanghui** [fungtion/DANN_py3#4]
Hello, in README.md, the environment is Pytorch 1.6 Python 3.8.5, but in Dockfile is Pytorch 1.0.1 and uses pytorch/pytorch:1.0.1-cuda10.0-cudnn7-runtime as base images. So which one is right and if we should use Pytorch 1.6,  then base images should use pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime, right?

**Comment by HuGanghui** [comment]
@fungtion I try to use Dockfile as following and it works:

```dockerfile
FROM pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime

# 配置pip源
COPY pip.conf /root/.pip/

RUN pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html \
 && mkdir /DANN

VOLUME ["/DANN/dataset", "/DANN/models"]

EXPOSE 22

COPY ./data_loader.py ./functions.py ./main.py ./model.py ./README.md ./test.py /DANN/

WORKDIR /DANN
```

and current Dockerfile has a problem that when install torchvision, it will download the latest version and then uninstall Pytorch 1.0.1 and install latest Pytorch version, which will cause final incompatible error. 

https://github.com/fungtion/DANN_py3/blob/5066239fe26c2a2c5c56eb3d6c1c5e3a138d468d/Dockerfile#L6

**Comment by fungtion** [comment]
@HuGanghui Thanks, it will be fixed later.
